### ISSUE TITLE
Android L support

### ISSUE THREAD

**Issue by matttbe** [MPTCP-smartphone-thesis/MultipathControl#1]
It is currently not planed to support Android 5 but it's possible that we will have to change a bit the way to use the cellular interface when the WiFi one is enabled.

Let's write here this tip to not forget it :-) 

Src: http://stackoverflow.com/a/28696825

> Well finally found solution for this.Trick was to use capability as NET_CAPABILITY_INTERNET.Which is same as "startUsingNetworkFeature(ConnectivityManager.TYPE_MOBILE, FEATURE_ENABLE_HIPRI);"
> 
> See the Firmware design here
> 
> ```
> builder.addCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET);
> builder.addTransportType(NetworkCapabilities.TRANSPORT_CELLULAR);
> ```
> 
> After this i am able to get onAvailable callback from system and later i set my process default network as mobile data.
> 
> Hence all the request goes over Mobile data even if wifi is on.WOW!
> 
> Note: This was not working in initial releases of Preview L.

**Comment by tarunmangla** [comment]
Can you direct on how to integrate this code to the existing code i.e. How to replace the deprecated startUsingNetworkFeature with this code?

**Comment by matttbe** [comment]
Hi @tarunmangla,

Two techniques are used to maintain active both LTE and WiFi connections:
- ask for High Priority feature (we need LTE "just in case"): https://github.com/MPTCP-smartphone-thesis/MultipathControl/blob/master/MultipathControl/src/be/uclouvain/multipathcontrol/ifaces/MobileDataMgr.java#L73
- create a "fake" connection with High Priority feature (we need LTE while this connection is alive): https://github.com/MPTCP-smartphone-thesis/MultipathControl/blob/master/MultipathControl/src/be/uclouvain/multipathcontrol/ifaces/MobileDataMgr.java#L115

Note that it is possible to check the version of Android in the code:

``` java
if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.LOLLIPOP) {
     // see https://developer.android.com/reference/android/os/Build.VERSION_CODES.html
}
```

**Comment by son2017** [comment]
@tarunmangla  can you please specfy the code how to implement on that in below code.

```java
	public void setMobileDataActive(boolean mEnabled) {
		if (Manager.DEBUG)
			Log.d(Manager.TAG, "setMobileDataActive " + new Date());

		ConnectivityManager cManager = (ConnectivityManager) context
				.getSystemService(Context.CONNECTIVITY_SERVICE);
		if (isMobileDataEnabled() && isWifiConnected() && mEnabled)
			cManager.startUsingNetworkFeature(ConnectivityManager.TYPE_MOBILE,
					"enableHIPRI");
		else
			cManager.stopUsingNetworkFeature(ConnectivityManager.TYPE_MOBILE,
					"enableHIPRI");
	}
```

**Comment by matttbe** [comment]
This should now be supported thanks to the new branch from @qdeconinck : https://github.com/MPTCP-smartphone-thesis/MultipathControl/tree/marshmallow
